### ISSUE TITLE
Keep some (90 days?) messages in main folder

### ISSUE THREAD

**Issue by 5TjpWBU2wkwHpFDb** [qwerty258/thunderbird-archive-by-time#2]
I love this extension! It is exactly the style that I want, but I want to keep the last 90 days in the main folder.

I will add a check around the move operation:
await messenger.messages.move(it.arrayMsgID, objectNewFolder);

Thanks.

**Comment by caspian-yez** [comment]
Unfortunately I'm not a web developer, this is my best effort: [7b7fd8f]. Help needed.
Retention days can be set in preference. So this addon will move emails older than retention days to subfolders only.
Restart needed for change to take effect.
You can download [0.3-RC1](https://github.com/qwerty258/thunderbird-archive-by-time/releases/tag/0.3-RC1) for test which is not uploaded to thunderbird addons website.

**Comment by caspian-yez** [comment]
Hi, [version 0.4](https://github.com/qwerty258/thunderbird-archive-by-time/releases/tag/0.4) only archive emails earlier than current year.

Closing this issue due to no response for long time.
